[project]
name = "midfide"
version = "0.1.0"
description = "Find out how mid are you in fide"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "polars>=1.27.1",
]
license = "MIT"

[dependency-groups]
dev = [
    "ruff>=0.11.7",
]
